# -*- coding: utf-8 -*-
"""Letsupgradeday5work.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TxfGBzkAh3UsAX_w-HEk3proquipWk7P
"""

# function to know a number is prime or not

def primeornot(n):
  if n > 1:
     for i in range(2, n):
       if (n % i) == 0:
        print(n, "-it is not a prime number")
        break
  else: 
    print(n, "-it is a prime number")

primeornot(2)