# -*- coding: utf-8 -*-
"""letsupgrade4thwork

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uip_86_W6P6gJFOWAO-9swu0pTAQTMSm
"""

# assignment 1 day 4

"""you all are pilots, you ahve to land a plane, the altitude required for landing is 1000ft, if it is less than that tell pilot to land the plane, or if it is more than that but less than 5000ft ask the pilot to 'come down to 1000ft', else if it is more than 5000ft ask the pilot to ;go around and try again later'."""

altitude = 1000
if altitude <= 1000 :
  print("it is safe to land")
elif altitude <= 5000 and altitude >1000 :
    print("come down to 1000 ft")
else:
     print("go around and try again later")